### ISSUE TITLE
EvidenceSynthesis was removed from CRAN so it is not installed via this R package

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Hades#15]
Issue:

The OHDSI EvidenceSynthesis R package was removed from CRAN so it is not installed via this R package

Background:

CRAN info:
https://cran.r-project.org/web/packages/EvidenceSynthesis/index.html

Package ‘EvidenceSynthesis’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/EvidenceSynthesis).

Archived on 2022-08-08 as requires archived package 'Cyclops'.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-08-08_check_results_EvidenceSynthesis.html).

Please use the canonical form https://cran.r-project.org/package=EvidenceSynthesis to link to this page.

Action:
Recommend updating this HADES R package to install the latest GitHub version of EvidenceSynthesis until it is made available again in CRAN

**Comment by schuemie** [comment]
Thanks! I've pushed a new version to CRAN

**Comment by schuemie** [comment]
It's now back in CRAN
