### ISSUE TITLE
Update macos install instructions

### ISSUE THREAD

**Issue by msuchard** [OHDSI/Hades#27]
1. `gfortran` link is out-dated
2. R v4.2.3 looks for `gfortran` in a different place than the R v4.3 gfortran installer puts it (at least on arm64 machines), so need to edit `.R/Makevars` to include `FLIBS`, e.g.

```
FLIBS=-L/opt/R/arm64/gfortran/lib
```

on my machine.

**Comment by msuchard** [comment]
i use `gfortran` from here: https://cran.r-project.org/bin/macosx/tools/

**Comment by schuemie** [comment]
@msuchard : could you help me understand how you got this working? I installed the`gfortran-12.2-universal.pkg` mentioned at the top of https://cran.r-project.org/bin/macosx/tools/ and used `sudo ln -s /opt/gfortran /usr/local/gfortran` to redirect R to the right location, but it comlains:
```
ld: warning: search path '/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0' not found
```
which indeed does not exist, but `/usr/local/gfortran/lib/gcc/x86_64-apple-darwin20/12.2.0`  does.

Any idea which gfortran install package I should install for Sonoma on an M3?

**Comment by schuemie** [comment]
(I tried the `gfortran-4.2.3.pkg` on the same page but got some invalid architecture error)

**Comment by msuchard** [comment]
arm64 compilers and whatnot get installed into `/opt/`.   please do not link to `/usr/local/` (a good OS will ignore these links as user-errors).    just update your `~/.R/Makevars` file.

mine reads:
```
F77 = /opt/gfortran/bin/gfortran
FC = /opt/gfortran/bin/gfortran

FLIBS=-L /opt/gfortran/lib
```

**Comment by schuemie** [comment]
Thanks @msuchard !
