### ISSUE TITLE
Bad Link In Instructions for installing RTools

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Hades#29]
Notes on installation send you to https://ohdsi.github.io/Hades/rSetup.html. 

RTool instructions say:
Go to https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html, and download the RTools installer.

But the link for Rtools actually points to 
https://ohdsi.github.io/Hades/%60r%20rToolsUrl%60

**Comment by schuemie** [comment]
Thanks Don!
