### ISSUE TITLE
Please start versioning all OHDSI packages

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/Hades#7]
Most OHDSI packages are not properly versioned. Please start versioning everything with tags or on CRAN to make the lifes of the users a little bit easier. Especially for a package like this one. I would like to pin the version so that my development stack doesn't go haywire when one of the dependencies has an incompatible update.

Everything used to work fine and now I get the following error when I install Hades:

```
namespace ‘SqlRender’ 1.6.8 is already loaded, but >= 1.7.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘CohortMethod’
* removing ‘/usr/local/lib/R/site-library/CohortMethod’
Error: Failed to install 'Hades' from GitHub:
  Failed to install 'CohortMethod' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmppnPysD/file6262b3842/CohortMethod_4.1.0.tar.gz’ had non-zero exit status
```

**Comment by ablack3** [comment]
Hi @sdebruyn, I think Hades packages to have versions both on CRAN and as github tags. For example [here](https://github.com/OHDSI/Andromeda/tags) are the version tags for Andromeda. Have you tried using the [renv package](https://rstudio.github.io/renv/articles/renv.html) to isolate the specific version of Hades packages you are using?
Using this package to install all of Hades is still a bit experimental I think. I just did it without any issues though.
